### ISSUE TITLE
Logo improvement

### ISSUE THREAD

**Issue by AndrickSilva** [AndrickSilva/Cloud-kitchen#10]
Require a good logo suggestion

**Comment by Cheeh1** [comment]
please assign this to me. i have a logo suggestion that will fit the brand and site. Here it is below.
![20221008_101910_0000](https://user-images.githubusercontent.com/87880831/194703009-0943d843-23bb-47e0-82bc-73dc523c93dd.png)

**Comment by Sakshy18** [comment]
Please assign this issue to me here is my logo suggestion:
![image](https://user-images.githubusercontent.com/84434398/194701481-4b441176-3ed1-43b3-b2c0-ad4a15d36a7d.png)

**Comment by Kritika30032002** [comment]
Is this still available?
You can assign this to me!!
