### ISSUE TITLE
Added read more functionality 

### ISSUE THREAD

**Issue by AndrickSilva** [AndrickSilva/Cloud-kitchen#9]
Added read more functionality to **CITIES WE DELIVER TO section**

**Comment by rajkumardongre** [comment]
Hello I want to work on this issue, can you assign it to me

**Comment by rajkumardongre** [comment]
can you tell me, Once somebody  clicks on the "Read more", What should happen, Currently UI looks like this

![q1](https://user-images.githubusercontent.com/77038993/194706264-316c2386-9ed5-4b73-8a63-25f52067c794.PNG)

**Comment by AndrickSilva** [comment]
> can you tell me, Once somebody clicks on the "Read more", What should happen, Currently UI looks like this
> 
> ![q1](https://user-images.githubusercontent.com/77038993/194706264-316c2386-9ed5-4b73-8a63-25f52067c794.PNG)

hide last 2 rows of the cities and on clicking on read more it show the 2 rows
